# Generated by Django 3.2.4 on 2021-06-27 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataDeVenda', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=9)),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Veiculos.veiculo')),
            ],
        ),
    ]
