# Generated by Django 3.2.4 on 2021-06-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='situacao',
            field=models.CharField(choices=[('1', 'Disponivel'), ('2', 'Vendido')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
